name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: install
      run: | 
        npm install
        yarn global add vuepress
        yarn add vuepress-theme-antdocs
        yarn docs:build
  
    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: valhir/valhir.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://docs.valhir.cn
